/*
 * This file is generated by jOOQ.
 */
package revolut.task.db;


import javax.annotation.Generated;

import revolut.task.db.tables.Accounts;
import revolut.task.db.tables.Transfers;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNTS</code>.
     */
    public static final Accounts ACCOUNTS = revolut.task.db.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>PUBLIC.TRANSFERS</code>.
     */
    public static final Transfers TRANSFERS = revolut.task.db.tables.Transfers.TRANSFERS;
}
