/*
 * This file is generated by jOOQ.
 */
package revolut.task.db.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import revolut.task.db.tables.Transfers;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransfersRecord extends UpdatableRecordImpl<TransfersRecord> implements Record6<Long, Long, Long, BigDecimal, String, OffsetDateTime> {

    private static final long serialVersionUID = 536241626;

    /**
     * Setter for <code>PUBLIC.TRANSFERS.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERS.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERS.FROM_ACCOUNT</code>.
     */
    public void setFromAccount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERS.FROM_ACCOUNT</code>.
     */
    public Long getFromAccount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERS.TO_ACCOUNT</code>.
     */
    public void setToAccount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERS.TO_ACCOUNT</code>.
     */
    public Long getToAccount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERS.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERS.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERS.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERS.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.TRANSFERS.DATE</code>.
     */
    public void setDate(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.TRANSFERS.DATE</code>.
     */
    public OffsetDateTime getDate() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, BigDecimal, String, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, BigDecimal, String, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Transfers.TRANSFERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Transfers.TRANSFERS.FROM_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Transfers.TRANSFERS.TO_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Transfers.TRANSFERS.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Transfers.TRANSFERS.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return Transfers.TRANSFERS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getFromAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getToAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getFromAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getToAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord value2(Long value) {
        setFromAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord value3(Long value) {
        setToAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord value5(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord value6(OffsetDateTime value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransfersRecord values(Long value1, Long value2, Long value3, BigDecimal value4, String value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransfersRecord
     */
    public TransfersRecord() {
        super(Transfers.TRANSFERS);
    }

    /**
     * Create a detached, initialised TransfersRecord
     */
    public TransfersRecord(Long id, Long fromAccount, Long toAccount, BigDecimal amount, String currency, OffsetDateTime date) {
        super(Transfers.TRANSFERS);

        set(0, id);
        set(1, fromAccount);
        set(2, toAccount);
        set(3, amount);
        set(4, currency);
        set(5, date);
    }
}
