/*
 * This file is generated by jOOQ.
 */
package revolut.task.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accounts implements Serializable {

    private static final long serialVersionUID = -1770494892;

    private Long       id;
    private String     name;
    private String     currency;
    private BigDecimal balance;

    public Accounts() {}

    public Accounts(Accounts value) {
        this.id = value.id;
        this.name = value.name;
        this.currency = value.currency;
        this.balance = value.balance;
    }

    public Accounts(
        Long       id,
        String     name,
        String     currency,
        BigDecimal balance
    ) {
        this.id = id;
        this.name = name;
        this.currency = currency;
        this.balance = balance;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Accounts (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(currency);
        sb.append(", ").append(balance);

        sb.append(")");
        return sb.toString();
    }
}
