/*
 * This file is generated by jOOQ.
 */
package revolut.task.db.tables.daos;


import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;
import javax.inject.Inject;
import javax.inject.Singleton;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import revolut.task.db.tables.Accounts;
import revolut.task.db.tables.records.AccountsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Singleton // custom code
public class AccountsDao extends DAOImpl<AccountsRecord, revolut.task.db.tables.pojos.Accounts, Long> {

    /**
     * Create a new AccountsDao with an attached configuration
     */
    @Inject // custom code
    public AccountsDao(Configuration configuration) {
        super(Accounts.ACCOUNTS, revolut.task.db.tables.pojos.Accounts.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(revolut.task.db.tables.pojos.Accounts object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<revolut.task.db.tables.pojos.Accounts> fetchById(Long... values) {
        return fetch(Accounts.ACCOUNTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public revolut.task.db.tables.pojos.Accounts fetchOneById(Long value) {
        return fetchOne(Accounts.ACCOUNTS.ID, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<revolut.task.db.tables.pojos.Accounts> fetchByName(String... values) {
        return fetch(Accounts.ACCOUNTS.NAME, values);
    }

    /**
     * Fetch records that have <code>CURRENCY IN (values)</code>
     */
    public List<revolut.task.db.tables.pojos.Accounts> fetchByCurrency(String... values) {
        return fetch(Accounts.ACCOUNTS.CURRENCY, values);
    }

    /**
     * Fetch records that have <code>BALANCE IN (values)</code>
     */
    public List<revolut.task.db.tables.pojos.Accounts> fetchByBalance(BigDecimal... values) {
        return fetch(Accounts.ACCOUNTS.BALANCE, values);
    }
}
