/*
 * This file is generated by jOOQ.
 */
package revolut.task.db.tables;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import revolut.task.db.Indexes;
import revolut.task.db.Keys;
import revolut.task.db.Public;
import revolut.task.db.tables.records.TransfersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transfers extends TableImpl<TransfersRecord> {

    private static final long serialVersionUID = 359131667;

    /**
     * The reference instance of <code>PUBLIC.TRANSFERS</code>
     */
    public static final Transfers TRANSFERS = new Transfers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransfersRecord> getRecordType() {
        return TransfersRecord.class;
    }

    /**
     * The column <code>PUBLIC.TRANSFERS.ID</code>.
     */
    public final TableField<TransfersRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.TRANSFERS.FROM_ACCOUNT</code>.
     */
    public final TableField<TransfersRecord, Long> FROM_ACCOUNT = createField("FROM_ACCOUNT", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSFERS.TO_ACCOUNT</code>.
     */
    public final TableField<TransfersRecord, Long> TO_ACCOUNT = createField("TO_ACCOUNT", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSFERS.AMOUNT</code>.
     */
    public final TableField<TransfersRecord, BigDecimal> AMOUNT = createField("AMOUNT", org.jooq.impl.SQLDataType.DECIMAL.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSFERS.CURRENCY</code>.
     */
    public final TableField<TransfersRecord, String> CURRENCY = createField("CURRENCY", org.jooq.impl.SQLDataType.CHAR(3).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TRANSFERS.DATE</code>.
     */
    public final TableField<TransfersRecord, OffsetDateTime> DATE = createField("DATE", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.precision(6).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.TRANSFERS</code> table reference
     */
    public Transfers() {
        this(DSL.name("TRANSFERS"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.TRANSFERS</code> table reference
     */
    public Transfers(String alias) {
        this(DSL.name(alias), TRANSFERS);
    }

    /**
     * Create an aliased <code>PUBLIC.TRANSFERS</code> table reference
     */
    public Transfers(Name alias) {
        this(alias, TRANSFERS);
    }

    private Transfers(Name alias, Table<TransfersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transfers(Name alias, Table<TransfersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Transfers(Table<O> child, ForeignKey<O, TransfersRecord> key) {
        super(child, key, TRANSFERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FK_TRANSFERS_ACCOUNTS_FROM_ACCOUNT_INDEX_E, Indexes.FK_TRANSFERS_ACCOUNTS_TO_ACCOUNT_INDEX_E, Indexes.PRIMARY_KEY_E);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TransfersRecord, Long> getIdentity() {
        return Keys.IDENTITY_TRANSFERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TransfersRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_E;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TransfersRecord>> getKeys() {
        return Arrays.<UniqueKey<TransfersRecord>>asList(Keys.CONSTRAINT_E);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TransfersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TransfersRecord, ?>>asList(Keys.FK_TRANSFERS_ACCOUNTS_FROM_ACCOUNT, Keys.FK_TRANSFERS_ACCOUNTS_TO_ACCOUNT);
    }

    public Accounts fkTransfersAccountsFromAccount() {
        return new Accounts(this, Keys.FK_TRANSFERS_ACCOUNTS_FROM_ACCOUNT);
    }

    public Accounts fkTransfersAccountsToAccount() {
        return new Accounts(this, Keys.FK_TRANSFERS_ACCOUNTS_TO_ACCOUNT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Transfers as(String alias) {
        return new Transfers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Transfers as(Name alias) {
        return new Transfers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transfers rename(String name) {
        return new Transfers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transfers rename(Name name) {
        return new Transfers(name, null);
    }
}
